import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
  {/* Banner Ad at the top */}
  <div className="w-full bg-gray-100 text-center py-2">
    <a
      href="https://example.com"
      target="_blank"
      rel="noopener noreferrer"
    >
      <img
        src="https://via.placeholder.com/728x90.png?text=Banner+Ad"
        alt="Banner Ad"
        className="mx-auto"
      />
    </a>
  </div>

  {children}
</body>
    </html>
  );
}
